version: '2'
 
services:
 
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:       #  追加 
      - ~/src/wordpress/:/var/www/html
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d